cabal-version:      3.0
name:               korigatachi
version:            0.0.0
synopsis:           eDSL targetting the Atari 2600
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             nks
maintainer:         nks@9k.vc
category:           Game
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall -fwrite-ide-info
    -- -ddump-splices -dth-dec-file

library
    import:           warnings

    exposed-modules:
        Korigatachi
        Korigatachi.Assembly.Control
        Korigatachi.Assembly.Demo
        Korigatachi.Assembly.Instruction
        Korigatachi.Assembly.Instruction.TH
        Korigatachi.Assembly.Pattern
        Korigatachi.Assembly.Operand
        Korigatachi.Atari.Model
        Korigatachi.Atari.Types
        Korigatachi.Bin
        Korigatachi.Control
        Korigatachi.Monad
        Korigatachi.Resolve
        Korigatachi.Resolve.Types
        Korigatachi.Types

    -- other-modules:

    -- other-extensions:

    build-depends:
        attoparsec,
        base,
        bytestring,
        containers,
        finite-typelits,
        optics,
        text,
        template-haskell,
        transformers,
        vector-sized,
        haskell-src-meta,
        haskell-src-exts,
        pretty-show

    hs-source-dirs:   src

    default-language: Haskell2010
    default-extensions:
        ImportQualifiedPost

executable korigatachi
    import:           warnings

    main-is:          Main.hs

    default-extensions:
        ImportQualifiedPost

    build-depends:
        base,
        korigatachi

    hs-source-dirs:   app

    default-language: Haskell2010

test-suite korigatachi-test
    import:           warnings

    default-language: Haskell2010

    other-modules: Korigatachi.Test

    type:             exitcode-stdio-1.0

    hs-source-dirs:   test

    main-is:          Main.hs

    build-depends:
        attoparsec,
        base,
        criterion,
        tasty,
        tasty-hunit,
        tasty-golden,
        tasty-smallcheck,
        tasty-quickcheck,
        tasty-program,
        text,
        bytestring,
        containers,
        korigatachi
